name: Medical Autopilot

on:
  schedule:
    - cron: "0 */4 * * *" # Запускати кожні 4 години
  workflow_dispatch: # Дозволити ручний запуск

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests python-dotenv

      - name: Run Autopilot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python autopilot.py
